#!/usr/bin/python
from daemon import Daemon
import sys
import time
import logging
from fan_control.fan_control import FanControl

PIDFILE = '/var/run/fan-control.pid'
LOGFILE = '/var/log/fan-control.log'

# Configure logging
logging.basicConfig(filename=LOGFILE,level=logging.DEBUG)


class FanControlDaemon(Daemon):

    def run(self):
        self.fan_control = FanControl()
        while True:
            fan_control.update()
            time.sleep(60)

if __name__ == "__main__":

    daemon = FanControlDaemon(PIDFILE)

    if len(sys.argv) == 2:

        if 'start' == sys.argv[1]:
            try:
                daemon.start()
            except:
                pass

        elif 'stop' == sys.argv[1]:
            print "Stopping ..."
            daemon.stop()

        elif 'restart' == sys.argv[1]:
            print "Restaring ..."
            daemon.restart()

        elif 'status' == sys.argv[1]:
            try:
                pf = file(PIDFILE,'r')
                pid = int(pf.read().strip())
                pf.close()
            except IOError:
                pid = None
            except SystemExit:
                pid = None

            if pid:
                print 'Fan Control is running as pid %s' % pid
            else:
                print 'Fan Control is not running.'

        else:
            print "Unknown command"
            sys.exit(2)
    else:
        print "usage: %s start|stop|restart|status" % sys.argv[0]
        sys.exit(2)


